### ISSUE TITLE
Allow configuring a custom title for directory tree

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/Diagnostics#126]
For example, the app group URL now shows up like:
![CleanShot 2022-07-28 at 13 39 30](https://user-images.githubusercontent.com/4329185/181496502-7911adcf-5eda-4d99-953a-7dc28257baff.jpg)

The UUID is not really descriptive.

**Comment by entunidotdeb** [comment]
Hi @AvdLee 
can i take this up and give it a try ?

**Comment by AvdLee** [comment]
@entunidotdeb totally! Happy to review your PR afterwards! 💯

**Comment by entunidotdeb** [comment]
@AvdLee  may we close this now ?

**Comment by AvdLee** [comment]
@entunidotdeb yes!
