### ISSUE TITLE
Getting these errors.. using Swift PM

### ISSUE THREAD

**Issue by OkiRules** [WeTransfer/Diagnostics#15]
<img width="1979" alt="Screen Shot 2019-12-05 at 8 26 20 pm" src="https://user-images.githubusercontent.com/18746541/70222079-8bbdd680-179d-11ea-9653-d58de68f6c0a.png">
<img width="1990" alt="Screen Shot 2019-12-05 at 8 26 13 pm" src="https://user-images.githubusercontent.com/18746541/70222080-8bbdd680-179d-11ea-81ae-7d6965585c03.png">

**Comment by AvdLee** [comment]
Thanks for reporting in, it's probably missing the foundation framework imports. I'll fix this!
