### ISSUE TITLE
Crash on App Launch "Thread 9: Fatal error: Trying to log a message while not set up"

### ISSUE THREAD

**Issue by victorlobe** [WeTransfer/Diagnostics#159]
In 5 out of 10 times the App crashes on launch with error:

`Thread 9: Fatal error: Trying to log a message while not set up`

on Line 166 
`            return assertionFailure("Trying to log a message while not set up")
`

In DiagnosticsLogger.swift.

Thanks

**Comment by reshadf** [comment]
is this something that can be looked into? Experiencing it as well
