### ISSUE TITLE
Make it possible to detect sensitive data

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/Diagnostics#17]
Try to find words like "token" and either filter it out or throw an error

**Comment by mustiikhalil** [comment]
What if we pass in an array of keys that we want to filter out? 
example:
`Diagnostics.Filter(keys: ["Token", "email"])`

**Comment by AvdLee** [comment]
@mustiikhalil thanks for the suggestion! I went for a slightly more advanced approach that is more flexible. See the attached PR 🙂

Let me know your thoughts!

**Comment by mustiikhalil** [comment]
Looks great!
