### ISSUE TITLE
DiagnosticsLogger makes app crash on iOS 18

### ISSUE THREAD

**Issue by hiddevdploeg** [WeTransfer/Diagnostics#177]
It seems like DiagnosticsLogger is crashing my app on launch on iOS 18. I know it's still in beta but just wanted to make you all aware :)

![CleanShot 2024-07-17 at 12 35 45@2x](https://github.com/user-attachments/assets/c650b42f-3a3d-4b2a-9838-45488111be28)

**Comment by doctorsaway** [comment]
Hey folks - are there any updates here? We seem to be facing the same issue :/

**Comment by jordibruin** [comment]
Happening for some users here on macOS 15 as well. Will strip it out for now.

**Comment by AvdLee** [comment]
This is solved in version 5.0.0. Upgrading RocketSim to 5.0.0 allowed me to solve this crash. See this commit: https://github.com/WeTransfer/Diagnostics/commit/90891220134d722921255d2b99a6f2168d06706c#diff-e373e2f3e74b7a9410110385545e25e11eb263b8ec89e147bf4224c9a1ec8c9fL238
