### ISSUE TITLE
Crash when trying to load the CSS

### ISSUE THREAD

**Issue by mustiikhalil** [WeTransfer/Diagnostics#21]
I added this framework to a demo app, and I am getting the following crash

```swift
        let bundle = Bundle(for: DiagnosticsLogger.self)
        let cssFile = bundle.url(forResource: "style", withExtension: "css")! // <- crash
        let css = try! String(contentsOf: cssFile, encoding: .utf8).minifiedCSS()
```

How to replicate the crash:
1- Create an iOS app
2- Use CocoaPods
3- just use the template code in the Readme

**Comment by AvdLee** [comment]
Thanks for reporting! I’ll fix this tomorrow 👌🏻
