### ISSUE TITLE
Still crashes on the CSS line

### ISSUE THREAD

**Issue by OscarGorog** [WeTransfer/Diagnostics#28]
This line is still crashing on 1.0.1, using Swift PM

<img width="1998" alt="Screen Shot 2019-12-07 at 9 39 47 am" src="https://user-images.githubusercontent.com/18746541/70361454-bc089080-18d5-11ea-9fcb-47cc7b78831b.png">

**Comment by AvdLee** [comment]
Did you do a clean build? I was able to reproduce it before but not anymore!

**Comment by AvdLee** [comment]
You're right, got it reproduced! Working on a fix now

**Comment by AvdLee** [comment]
Unfortunately, this is due to the fact that SPM does not support resources yet: https://forums.swift.org/t/draft-proposal-package-resources/29941

I'll work on a temporary fix this Monday to not have the requirement of including the complete CSS file.

**Comment by OscarGorog** [comment]
Can’t you just put the CSS into a plain String in the code?

Thanks,
Oscar

**Comment by AvdLee** [comment]
@OscarGorog yes, that's exactly what I was planning to do and did! 🙂
