### ISSUE TITLE
Question: Workaround for users who don't use Apple Mail

### ISSUE THREAD

**Issue by simonseyer** [WeTransfer/Diagnostics#29]
_This is not a bug report but rather a question related to your project where I'm interested if you, or anyone else reading this, found a good workaround._

We are also using `MFMailComposeViewController` in our app to let users send feedback. However, we ran into the issue that when you don't use Apple Mail (I don't) you cannot use `MFMailComposeViewController`. `canSendMail` will return `false` in this case.

We will now probably just expose an endpoint in our backend to receive user feedback and don't use the builtin mail composer. However, we would prefer to stick to the current solution. Since this project is also heavily impacted by this, I would be curious if you also ran into this issue and might have a creative idea how to get around it.

**Comment by AvdLee** [comment]
Slightly related to #30. We could make the framework more flexible to work with other solutions.

Therefore, closing this one in favor of #30. Let me know if that's fine for you as well!

**Comment by simonseyer** [comment]
:+1: Missed this ticket or rather didn't see the connection when reading the title.

**Comment by AvdLee** [comment]
No worries, it was created after yours! 🙂 Thanks!
