### ISSUE TITLE
Support different platforms/APIs

### ISSUE THREAD

**Issue by a1cooke** [WeTransfer/Diagnostics#30]
👋 Love the idea of this project.

I was wondering would you be open to the idea of support sending these via other channels other than email?

I was thinking maybe supporting a pluggable API to support different APIs for reporting issues.

Happy to explore the idea and open a PR but wanted to see if it was inline with your vision for this?

**Comment by AvdLee** [comment]
Definitely! It would make this framework even more valuable. As long as we make sure it keeps working with email it's fine! 

Would love to see you submit a PR for that 🙂

**Comment by AvdLee** [comment]
@a1cooke I was wondering whether you made any progress already!

**Comment by a1cooke** [comment]
I've started looking at it but got distracted with Christmas/Holiday season. 

From your perspective, for none Apple Mail users, should a UI be presented a kin to the current experience?

**Comment by AvdLee** [comment]
Maybe we can make use of the share extension? I wouldn't want to add a whole lot of UI code to this framework.

The user could then decide what to do with the file. However, the more I think about this the more I'm asking myself whether this should be something to include in this framework 🤔 

What do you think?
