### ISSUE TITLE
Support for Apple Watch App Logs

### ISSUE THREAD

**Issue by cnstoll** [WeTransfer/Diagnostics#33]
Hi,

I'm starting to use this library in my app and I think it's pretty sweet! I extended the Diagnostic Logger piece to also support Apple Watch app logs by writing a log file on the watch and periodically transferring the file over to the iPhone, where it can be included in a report alongside the iPhone logs.

Is that something ya'll would want me to put up a PR for? Just figured I would ask first.

Thanks,

- Conrad

**Comment by AvdLee** [comment]
That's awesome! Yeah, it would be great to have that as an option in the library. Maybe not as a default reporter but definitely as an opt-in.

If you would like to add it to the project, please do! Happy to review it 🙂

**Comment by AvdLee** [comment]
@cnstoll any progress so far? Would be nice to have it in the framework!

**Comment by cnstoll** [comment]
Sorry for the delay. I have this working in my app and I've just been testing it out. I'll try to get it cleaned up and get a PR ready. It may take me a few weeks because I'll be traveling a bit, but I am planning to do it!
