### ISSUE TITLE
Get warning for file 'style.css' after building

### ISSUE THREAD

**Issue by davidsteppenbeck** [WeTransfer/Diagnostics#39]
Details are in the image. I resolved it for the time being by removing file 'style.css' from the Xcode project. (Installed Diagnostics 1.2 using Cocoapods 1.8 and Xcode 11.3.)

<img width="1735" alt="DiagnosticsWarning" src="https://user-images.githubusercontent.com/59126213/71322557-b3f94500-24c0-11ea-9758-cdd772fc66e1.png">

**Comment by davidsteppenbeck** [comment]
@AvdLee just updated - thanks for the fix!

**Comment by AvdLee** [comment]
@davidsteppenbeck you're welcome, thanks for reporting it! 💪
