### ISSUE TITLE
No indication of AM or PM in log times

### ISSUE THREAD

**Issue by davidsteppenbeck** [WeTransfer/Diagnostics#40]
The times provided in the logs give no indication of whether they are AM or PM. Would be improved if 24-hour clock was used.

<img width="183" alt="LogDateTime" src="https://user-images.githubusercontent.com/59126213/71322782-53b7d280-24c3-11ea-85b6-f76ba0f9dfc9.png">

**Comment by AvdLee** [comment]
Thanks for reporting this. Indeed, this can be improved!

**Comment by AvdLee** [comment]
Fixed with https://github.com/WeTransfer/Diagnostics/pull/46
