### ISSUE TITLE
No public read access to var `DiagnosticsLogger.standard.isSetup`

### ISSUE THREAD

**Issue by davidsteppenbeck** [WeTransfer/Diagnostics#41]
There is currently no public read access to var `DiagnosticsLogger.standard.isSetup` (file `DiagnosticsLogger.swift` line `40`), which could be useful when developing and debugging. I suggest adding public read access using:

    /// Whether the logger is setup and ready to use.
    public static func isSetUp() -> Bool {
        return standard.isSetup
    }

**Comment by AvdLee** [comment]
Feel free to open a PR for this! It should be really easy to do so :)

**Comment by davidsteppenbeck** [comment]
OK, happy to contribute!
