### ISSUE TITLE
Support for iOS 10.0

### ISSUE THREAD

**Issue by sairamkotha** [WeTransfer/Diagnostics#42]
Thanks for open sourcing Diagnostics.
Any specific reason for making it compatible for iOS 11 above?
I cloned and made minimum target as iOS 10.0 & I found only one error it is sortedKeys for json. 
Do you mind if I raise PR to support for iOS 10 & above?

**Comment by AvdLee** [comment]
I assume you're not alone in the sense that more users like to support iOS 10! So yeah, if it's not too much I would love to receive a PR for iOS 10 support :)

**Comment by sairamkotha** [comment]
Sure. I will raise PR in sometime. Thanks @AvdLee.

**Comment by sairamkotha** [comment]
Raised PR [43](https://github.com/WeTransfer/Diagnostics/pull/43)
