### ISSUE TITLE
Explore iOS 14 MetricKit possibilities

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/Diagnostics#73]
See https://www.chimehq.com/blog/metrickit-crash-reporting

It might help us to improve the Diagnostics reports with extra information.

**Comment by Nikhil0487** [comment]
@AvdLee I have gone through the link and its interesting. If you have any outline for MetricKit things you would consider for adding to this project, I would like to help you in it.

**Comment by AvdLee** [comment]
@Nikhil0487 that's great! Yeah, I was hoping to mainly add information regarding crash reports. It would be very useful to read out extra information for specific users that have issues and crashes. This should be possible with MetricKit if I recall correctly.

Is that something you can look into?

**Comment by Nikhil0487** [comment]
@AvdLee 

Sure. I would look into the MetricKit framework and see what additional information we could give users that's not currently given by this repository. 

Is that okay?

**Comment by AvdLee** [comment]
Yes, perfect! Keep us posted on your progress, would love to learn from your experiences 🙂

**Comment by Nikhil0487** [comment]
@AvdLee 

Below is the overall summary:

Good:
1. Crash/termination reports can be obtained per 24 hours
2. Multiple termination/crash types are reported,
3. https://github.com/ChimeHQ/Meter can be a reference for this framework,
4. Native in-process crash diagnostics,


Meh:
1. Diagnostic payload JSON structure can be better,
2. Symbolication is not supported for stack trace,
3. iOS 14+ only,
4. Reliability is unknown, 
5. Does not currently expose any information about uncaught exceptions

**Comment by AvdLee** [comment]
Ideally, we would implement this without an external dependency. Uncaught exceptions are already catched, so it's fine if we miss those. Reliability and iOS 14 are OK risks to take, we can try it out and always revert if needed.

In other words, I would love to continue with this and see what the reports can bring us!

**Comment by Nikhil0487** [comment]
@AvdLee 

Okay. 
Then i will start experimenting and will update/consult/share things here.

**Comment by wetransferplatform** [comment]
The pull request #89 that closed this issue was merged and released as part of [Release 1.10.0](https://github.com/WeTransfer/Diagnostics/releases/tag/1.10.0) :rocket:
Please let us know if the functionality works as expected as a reply here. If it does not, please open a new issue. Thanks!<p align="right"><i>Generated by <a href="https://github.com/WeTransfer/GitBuddy">GitBuddy</a></i></p>
