### ISSUE TITLE
About assertionFailure

### ISSUE THREAD

**Issue by longjianjiang** [WeTransfer/Diagnostics#74]
Is there necessary to use `assertionFailure` on unexpected condition at DiagnosticLogger.swift. May be use `print` more friendly.

**Comment by longjianjiang** [comment]
@AvdLee

**Comment by AvdLee** [comment]
@longjianjiang assertion failures help during debugging. Whenever they're triggered it means that the logger is not setup correctly.

Note that assertion failures are not triggered in a release build so they would never cause any harm to end-users.

Let me know if that answers your question!

**Comment by longjianjiang** [comment]
Thanks! @AvdLee
