### ISSUE TITLE
Diagnostics.xcodeproj is Missing

### ISSUE THREAD

**Issue by LeoSnek** [WeTransfer/Diagnostics#98]
I'm trying to update to the latest version of this library but the `Diagnostics.xcodeproj` file is missing from the repo. Was this deliberate? If so can the installation instructions be updated please?

**Comment by LeoSnek** [comment]
Yep that works, however we'd like to do manually "properly", i.e. no submodules. Is this possible? Would be good if you can just add the Diagnostics.xcodeproj file back in

**Comment by AvdLee** [comment]
> Yep that works, however we'd like to do manually "properly", i.e. no submodules. Is this possible? Would be good if you can just add the Diagnostics.xcodeproj file back in

There's no real difference between using a local SPM package or a local `xcodeproj`. It's really just dragging the Diagnostics directory into your project instead of the `xcodeproj`. Have you tried that out?

**Comment by LeoSnek** [comment]
I did yeah, I tried it in two ways. Following your instructions it all works just fine. However, we don't want to add the library as a submodule just add the files and go. When I added the folder manually Xcode recognised it as a SPM package but the framework didn't show up when trying to add to the target's frameworks.

That doesn't really make sense to me though, any idea why there would be a difference?

**Comment by LeoSnek** [comment]
Okay I'll give it another try tomorrow, maybe I did something wrong! Happy to use it as a SPM package if it works 👍🏻

**Comment by LeoSnek** [comment]
Right I managed to get it working, it wasn't working locally because when I was trying to add the folder manually I had renamed it from 'Diagnostics-master' to 'Diagnostics'. For some reason Xcode doesn't like this!

**Comment by AvdLee** [comment]
All good, glad it worked out in the end!
